blank_issues_enabled: true
contact_links:
  - name: Official Server of Xylar Inc.
    url: https://discord.gg/CQ6Et3Kws7
    about: Join our official Discord server for support and community discussion.
